// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtahCarSafety.Models;

namespace UtahCarSafety.Migrations.CrashesDb
{
    [DbContext(typeof(CrashesDbContext))]
    partial class CrashesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UtahCarSafety.Models.City", b =>
                {
                    b.Property<string>("CITY")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("CITY");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("UtahCarSafety.Models.Crash", b =>
                {
                    b.Property<int>("CRASH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BICYCLIST_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("COMMERCIAL_MOTOR_VEH_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("COUNTY_NAME")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CRASH_DATETIME")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CRASH_SEVERITY_ID")
                        .HasColumnType("int");

                    b.Property<bool>("DISTRACTED_DRIVING")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DOMESTIC_ANIMAL_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DROWSY_DRIVING")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DUI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IMPROPER_RESTRAINT")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("INTERSECTION_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("LAT_UTM_Y")
                        .HasColumnType("float");

                    b.Property<float>("LONG_UTM_X")
                        .HasColumnType("float");

                    b.Property<string>("MAIN_ROAD_NAME")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("MILEPOINT")
                        .HasColumnType("float");

                    b.Property<bool>("MOTORCYCLE_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NIGHT_DARK_CONDITION")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OLDER_DRIVER_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OVERTURN_ROLLOVER")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PEDESTRIAN_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ROADWAY_DEPARTURE")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ROUTE")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("SINGLE_VEHICLE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TEENAGE_DRIVER_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UNRESTRAINED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WILD_ANIMAL_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WORK_ZONE_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CRASH_ID");

                    b.ToTable("Crashes");
                });
#pragma warning restore 612, 618
        }
    }
}
